USE DBAPPSAUDE
GO

IF OBJECT_ID ( 'dbo.Imagem', 'U' ) IS NOT NULL  
BEGIN
	DROP TABLE Imagem
END

CREATE TABLE Imagem
(
	  IdImagem   INT   NOT NULL IDENTITY(1,1)
	 ,GuidImagem UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID()
)

ALTER TABLE Imagem
ADD CONSTRAINT PkImagem  PRIMARY KEY (IdImagem)